### PR TITLE
Fixing unittest and adding directory structure

### PR DESCRIPTION
**Pull request by goujin**
**Why the change?**
Unittest couldn't work as is even if the biped code was fixed.
Extra structure is needed later in this repo also. So I dealt with that too at the same time.
**What has changed?**
Only sort should fail once the biped code is fixed. There is also a readme to the repo and now I can push assigments to the associated directory with documentation on the course material when the time comes.

### CODE REVIEW

**Comment by MUlRA** [comment]
Theres 2 conflict that im unable to resolve

**Comment by MUlRA** [comment]
found the issue to get it resolve, might need to look if i didnt delete anything that we wanted to keep

**Comment by goujin** [comment]
Normallement cette pr serait juste merge dans main  et tu repartirais de main dans une autre branche. Les tests ne sont pas censé changé dans tes commits.

**Review by MUlRA — APPROVED** [review]
Aproove

**Pull request merged**
